// ---------------------------------------------------------------------------
// PlainTextExtractor.cs
// The formats that are already text, plus HTML, which is text wearing tags.
//
// Encoding is detected from a byte-order mark and otherwise assumed to be UTF-8
// with replacement rather than failure. A data lake accumulates files written
// by two decades of tools, and a run that threw on the first Latin-1 CSV would
// index nothing; a few replacement characters in one file's body is the better
// trade, and the file is still findable by everything else about it.
// ---------------------------------------------------------------------------

namespace Connector.Extraction;

using System.Text;
using System.Text.RegularExpressions;

/// <summary>Text, CSV, JSON, XML, logs and HTML.</summary>
public sealed partial class PlainTextExtractor : ITextExtractor
{
    private static readonly HashSet<string> MarkupExtensions =
        new(StringComparer.OrdinalIgnoreCase) { "htm", "html", "xhtml" };

    /// <inheritdoc/>
    public IReadOnlyCollection<string> Extensions { get; } = new[]
    {
        "txt", "md", "csv", "tsv", "json", "xml", "log", "yaml", "yml", "ini", "conf", "sql", "htm", "html", "xhtml",
    };

    /// <inheritdoc/>
    public async Task<ExtractionResult> ExtractAsync(
        Stream content, string fileName, CancellationToken cancellationToken)
    {
        using var reader = new StreamReader(
            content,
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: false),
            detectEncodingFromByteOrderMarks: true,
            leaveOpen: true);

        string text = await reader.ReadToEndAsync(cancellationToken);

        string extension = Path.GetExtension(fileName).TrimStart('.');

        if (MarkupExtensions.Contains(extension))
        {
            text = StripMarkup(text);
        }

        return ExtractionResult.Success(text);
    }

    /// <summary>
    /// Reduces HTML to its readable text.
    ///
    /// Deliberately not an HTML parser. Graph would accept the markup as html
    /// content, but this connector indexes everything as text so that one
    /// truncation rule and one redaction story cover every file type; and a real
    /// parser is a dependency for something a lake's HTML - mostly reports
    /// generated by a job - does not need.
    /// </summary>
    /// <param name="html">The document.</param>
    /// <returns>Its text.</returns>
    public static string StripMarkup(string html)
    {
        if (string.IsNullOrEmpty(html))
        {
            return string.Empty;
        }

        // Script and style hold text that is not prose and would otherwise be
        // indexed as if it were.
        string text = ScriptOrStyle().Replace(html, " ");
        text = Tags().Replace(text, " ");
        text = System.Net.WebUtility.HtmlDecode(text);

        return Whitespace().Replace(text, " ").Trim();
    }

    [GeneratedRegex(@"<(script|style)\b[^>]*>.*?</\1>", RegexOptions.IgnoreCase | RegexOptions.Singleline)]
    private static partial Regex ScriptOrStyle();

    [GeneratedRegex("<[^>]+>", RegexOptions.Singleline)]
    private static partial Regex Tags();

    [GeneratedRegex(@"\s+")]
    private static partial Regex Whitespace();
}
